/**
 * Where each surface's data actually comes from.
 *
 * The dashboard renders two kinds of data side by side. The professional
 * profile is real: it is written by the user, stored in Postgres, and read
 * back. Everything else is generated by `lib/data/mock/db.ts` — a seeded
 * fixture that produces plausible pipelines, listings, leads and commissions.
 *
 * Rendered identically, those are indistinguishable. A pipeline of $10.8M and
 * a projected GCI of $309,645 look exactly like a real business, and someone
 * could reasonably act on them. This module is the single declaration of which
 * is which, so a label can never drift from the truth it describes.
 *
 * It is also the switch. When a domain gets a real backend, changing one entry
 * here removes its sample chips, removes its page notice, and re-enables its
 * write actions together — rather than leaving a stale "Sample" badge on real
 * data, which would be its own kind of lie.
 *
 * Dependency-free and framework-free on purpose: server components, client
 * components and tests all read the same table.
 */

export type DataDomain =
  | "transactions"
  | "listings"
  | "leads"
  | "calendar"
  | "documents"
  | "reports"
  | "messages"
  | "ai"
  | "market"
  | "agents"
  | "team"
  | "brokerage"
  | "integrations"
  /** The professional profile — genuinely persisted. */
  | "profile";

export type Provenance = "sample" | "live";

interface DomainRecord {
  provenance: Provenance;
  /** How the domain is named to a user. */
  label: string;
  /**
   * What is missing before this domain is real.
   *
   * Shown when a write is unavailable, so the user is told WHY rather than
   * finding a control that silently does nothing.
   */
  pending: string;
}

const DOMAINS: Record<DataDomain, DomainRecord> = {
  transactions: {
    provenance: "sample",
    label: "Transactions",
    pending: "transactions are connected",
  },
  listings: {
    provenance: "sample",
    label: "Listings",
    pending: "the MLS connection is live",
  },
  leads: { provenance: "sample", label: "Leads", pending: "leads are connected" },
  calendar: { provenance: "sample", label: "Calendar", pending: "the calendar is connected" },
  documents: { provenance: "sample", label: "Documents", pending: "document storage is connected" },
  reports: { provenance: "sample", label: "Reports", pending: "transactions are connected" },
  messages: { provenance: "sample", label: "Messages", pending: "messaging is connected" },
  ai: { provenance: "sample", label: "AI", pending: "the assistant is connected" },
  market: { provenance: "sample", label: "Market data", pending: "market data is connected" },
  agents: { provenance: "sample", label: "Team production", pending: "transactions are connected" },
  team: { provenance: "sample", label: "Team", pending: "team management is connected" },
  brokerage: { provenance: "sample", label: "Brokerage", pending: "brokerage records are connected" },
  integrations: { provenance: "sample", label: "Integrations", pending: "integrations are connected" },

  // The one real domain. Written by the user, stored in Postgres, read back.
  // It must never be labelled as sample — mislabelling real data would be the
  // same defect this module exists to prevent, pointed the other way.
  profile: { provenance: "live", label: "Professional profile", pending: "" },
};

export function provenanceOf(domain: DataDomain): Provenance {
  return DOMAINS[domain].provenance;
}

export function isSample(domain: DataDomain): boolean {
  return DOMAINS[domain].provenance === "sample";
}

export function domainLabel(domain: DataDomain): string {
  return DOMAINS[domain].label;
}

/**
 * Whether a domain may be written to.
 *
 * Sample domains cannot. Their adapters DO accept writes — they mutate an
 * in-memory fixture and bump a version counter, so the change appears on
 * screen and is gone on the next reload. That is worse than showing invented
 * numbers: the user believes they entered something. Until a domain has real
 * storage, its write controls are disabled and say why.
 */
export function canWrite(domain: DataDomain): boolean {
  return DOMAINS[domain].provenance === "live";
}

/** "Available once transactions are connected." Empty for live domains. */
export function writeDisabledReason(domain: DataDomain): string {
  const record = DOMAINS[domain];
  if (record.provenance === "live") return "";
  return `Available once ${record.pending}.`;
}

/** The one-line notice shown under a sample-backed page's title. */
export function sampleNotice(domain: DataDomain): string {
  const record = DOMAINS[domain];
  if (record.provenance === "live") return "";
  return `${record.label} shows sample data — not your live business. Nothing here is saved.`;
}

/** Every domain still on sample data. Used by tests and diagnostics. */
export function sampleDomains(): DataDomain[] {
  return (Object.keys(DOMAINS) as DataDomain[]).filter((d) => isSample(d));
}

/**
 * The domain a route's page is backed by, or null when it needs no notice.
 *
 * Null covers two different cases, and conflating them would be wrong:
 *
 *   Home and Settings are MIXED. Home renders the real profile card beside
 *   sample widgets; Settings renders the real profile beside sample team and
 *   brokerage sections. A page-level "this is sample data" banner would be
 *   false on the real half, so those surfaces label their sample parts
 *   individually instead — the widget chips and the section notices.
 *
 *   Onboarding is entirely real and needs nothing.
 *
 * Paths are matched WITHOUT the `/dashboard` basePath, which is what
 * `usePathname()` returns inside this zone.
 */
export function domainForPath(pathname: string): DataDomain | null {
  const path = pathname.replace(/\/+$/, "") || "/";
  const table: Array<[string, DataDomain]> = [
    ["/transactions", "transactions"],
    ["/listings", "listings"],
    ["/leads", "leads"],
    ["/calendar", "calendar"],
    ["/documents", "documents"],
    ["/reports", "reports"],
    ["/messages", "messages"],
    ["/ai", "ai"],
  ];
  for (const [prefix, domain] of table) {
    if (path === prefix || path.startsWith(`${prefix}/`)) {
      return isSample(domain) ? domain : null;
    }
  }
  return null;
}
